### ISSUE TITLE
Friends list

### ISSUE THREAD

**Issue by UNOMAHANLYON** [Hungover-Software/night_out_v2#4]
Add ability to manipulate the friends collection.

**Comment by Calaennis** [comment]
Friend requests can be sent out.
8199c0426cc4e8fad131a660567412c5bc2b4931

**Comment by Calaennis** [comment]
Checks placed on sending friend requests.
b074a5bc7e4e299c29ad473a696227851a57c9c6

**Comment by Calaennis** [comment]
Functionality seems to be present. Closing.

**Comment by Calaennis** [comment]
Some changes were made. Making it more secure, basically. Client only has access to their friends and friend requests.
13f5e1a01aeab8af640e41104e00e0251fc400a4
